name: Build docs
on:
  release:
  workflow_dispatch:
jobs:
  docs:
    name: Generate docs
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 14
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - run: yarn docs
      - run: 'echo "tyvn.js.org" >> ./docs/CNAME'
      - run: yarn del-cli ~/actions/temp/docs
      - run: mkdir -p ~/actions/temp/docs
      - run: mv ./docs/* ~/actions/temp/docs
      - run: yarn del-cli ./docs
      - uses: actions/checkout@v2
        with:
          ref: docs
      - run: mv ~/actions/temp/docs/* ./docs
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add docs
          git commit -m "generated docs"
          git push origin docs
