name: Build docs
on:
  release:
  workflow_dispatch:
jobs:
  docs:
    name: Generate docs
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 14
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn docs
      - uses: actions/cache@v2
        with:
          path: docs
          key: ${{ runner.os }}-docs-cache
      - run: yarn del-cli ./docs
      - uses: actions/checkout@v2
        with:
          ref: docs
      - uses: actions/cache@v2
        with:
          path: docs
          key: ${{ runner.os }}-docs-cache
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add docs
          git commit -m "generated docs"
          git push origin docs